#!/bin/bash -
#
# simple-api
#
# Temporary script to turn on or off SimpleAPI support for get, kill, order, and set on YottaDB r1.20 or newer
# This script will go away once extensive testing of the SimpleAPI support has been finished
#
# Call with -off to turn off SimpleAPI support, and go back to using the call-in interface
#    E.g. ./simple-api -off
# Call with -on to turn on SimpleAPI support for get, kill, order, and set APIs
#    E.g. ./simple-api -on

[[ -n $ydb_dist ]] && DIST=$ydb_dist || DIST=${gtm_dist:-.}
[[ -e $DIST/ydb ]] && API=1 || API=0

if [[ $1 == '-off' ]]
then
    sed -i "s/'YDB_SIMPLE_API=.*'/'YDB_SIMPLE_API=0'/g" ./binding.gyp

    echo YottaDB SimpleAPI support disabled

    npm install
elif [[ $1 == '-on' ]]
then
    [[ $API == 0 ]] && echo -e "YottaDB SimpleAPI support cannot be enabled\n" && exit 1

    sed -i "s:'YDB_SIMPLE_API=.*':'YDB_SIMPLE_API=<!(if [ -e \"<(gtm_dist)/ydb\" ]; then echo 1; else echo 0; fi)':g" ./binding.gyp

    echo YottaDB SimpleAPI support enabled

    npm install
else
    echo -e "Usage: $0 -off|-on\n"
fi

exit 0
