#!/bin/bash -
#
# try-simple-api
#
# Temporary script to enable SimpleAPI support for get, kill, order, and set on YottaDB r1.20 or newer
#
# Call with no arguments to try the experimental SimpleAPI support for get, kill, order, and set APIs
#    E.g. ./try-simple-api
# Call with -r to revert the SimpleAPI support, and go back to using the call-in interface
#    E.g. ./try-simple-api -r

[[ -n $ydb_dist ]] && DIST=$ydb_dist || DIST=${gtm_dist:-.}
[[ -e $DIST/ydb ]] && API=1 || API=0

if [[ $1 == '-r' ]]
then
    sed -i "s/'YDB_SIMPLE_API=.*'/'YDB_SIMPLE_API=0'/g" ./binding.gyp

    echo YottaDB SimpleAPI support disabled
else
    sed -i "s/'YDB_SIMPLE_API=.*'/'YDB_SIMPLE_API=$API'/g" ./binding.gyp

    [[ $API == 1 ]] && echo YottaDB SimpleAPI support enabled || echo YottaDB SimpleAPI support cannot be enabled
fi

npm install

exit 0
